language: java
jdk:
  - oraclejdk7
before_install:
 - "echo $JAVA_OPTS"
 - "mvn install -DskipTests -B"
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1024m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
